spring:
  datasource:
    url: jdbc
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



